ANALYST = "ANALYST"
SYNTHESIZER = "SYNTHESIZER"
VALIDATOR = "VALIDATOR"
ORCHESTRATOR = "ORCHESTRATOR"
ADVERSARIAL = "ADVERSARIAL"
META = "META"

ALL_ROLES = {
    ANALYST,
    SYNTHESIZER,
    VALIDATOR,
    ORCHESTRATOR,
    ADVERSARIAL,
    META
}
